#ifndef _CONFIG_HPP_
#define _CONFIG_HPP_

// GSC MODULES
#define COMPILE_BOTS 0
#define COMPILE_ENTITY 0
#define COMPILE_EXEC 0
#define COMPILE_MEMORY 0
#define COMPILE_MYSQL_DEFAULT 0
#define COMPILE_MYSQL_VORON 0
#define COMPILE_PLAYER 0
#define COMPILE_SQLITE 0
#define COMPILE_UTILS 0
#define COMPILE_WEAPONS 0

// RATE LIMITER
#define COMPILE_RATELIMITER 1

#endif
